default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  # password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  # host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  # port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # url: postgresql://rails_7_baseapi_user:L4UnRcvyQsV7Bg5fAAcD43fhZOFoVH7v@dpg-cuiqnq3qf0us73dstl5g-a.oregon-postgres.render.com/rails_7_baseapi

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

# For production is recommended to set DATABASE_URL env variable.
# It will take precedence over the config defined here.
# https://edgeguides.rubyonrails.org/configuring.html#connection-preference
production:
  url: <%= ENV['DATABASE_URL'] %>
  # url: postgresql://rails_7_baseapi_user:L4UnRcvyQsV7Bg5fAAcD43fhZOFoVH7v@dpg-cuiqnq3qf0us73dstl5g-a.oregon-postgres.render.com/rails_7_baseapi
